// functions/api/config.js

export async function onRequest(context) {
    // 1. METADATA
    const streamprotected_cb2_METADATA = [
        { "streamprotectedtrack_c-ee2": 1, "english_name": "The Opening", "description": "Revealed in Mecca, this is the fundamental prayer of Islam, summarizing the core relationship between God and humanity. It is recited in every unit of prayer. (7 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 2, "english_name": "The Cow", "description": "The longest streamprotected_cb2, revealed in Medina. It establishes Islamic laws, recounts the stories of Moses (Peace be upon him), and guides the new Muslim community. (286 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 3, "english_name": "The Family of Imran", "description": "A Medinan streamprotectedtrack_c-ee2 focusing on the Oneness of God, the family of Mary (Peace be upon her) and Jesus (Peace be upon him), and lessons from the Battle of Uhud. (200 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 4, "english_name": "The Women", "description": "Revealed in Medina after the Battle of Uhud, addressing the rights of women, care for orphans, inheritance laws, and the protection of the vulnerable within society. (176 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 5, "english_name": "The Table Spread", "description": "One of the last revealed streamprotected_cb2s, finalizing dietary laws and discussing the miracle of the table requested by the disciples of Jesus (Peace be upon him) and the fulfillment of covenants. (120 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 6, "english_name": "The Cattle", "description": "A late Meccan streamprotected_cb2 emphasizing pure monotheism, rejecting superstition, and detailing the nature of God's infinite power over creation. (165 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 7, "english_name": "The Heights", "description": "A Meccan streamprotectedtrack_c-ee2 detailing the history of prophets from Adam (Peace be upon him) to Moses (Peace be upon him), warning against arrogance and describing the Day of Judgment. (206 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 8, "english_name": "The Spoils of War", "description": "Revealed after the Battle of Badr, clarifying the ethics of warfare, the distribution of spoils, and the importance of placing full trust in God. (75 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 9, "english_name": "The Repentance", "description": "A Medinan text issued before the Tabuk expedition, addressing treaty violations by polytheists and the issue of hypocrisy; it is the only streamprotected_cb2 that does not begin with 'Bismillah'. (129 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 10, "english_name": "Jonah", "description": "A Meccan streamprotected_cb2 emphasizing God's Oneness and citing the story of the people of Jonah (Peace be upon him), who were saved by their timely repentance. (109 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 11, "english_name": "Hud", "description": "Revealed during a difficult period in Mecca, recounting stories of previous prophets like Noah (Peace be upon him) and Hud (Peace be upon him) to comfort the Prophet Muhammad (Peace be upon him). (123 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 12, "english_name": "Joseph", "description": "A unique Meccan streamprotected_cb2 devoted entirely to the story of Joseph (Peace be upon him), illustrating patience, divine destiny, and family reconciliation. (111 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 13, "english_name": "The Thunder", "description": "Revealed in Medina, utilizing natural phenomena like thunder to argue for the existence of God and the absolute truth of the resurrection. (43 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 14, "english_name": "Abraham", "description": "A Meccan streamprotectedtrack_c-ee2 highlighting the prayer of Abraham (Peace be upon him) for the sanctuary of Mecca and contrasting the gratitude of believers with the ingratitude of disbelievers. (52 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 15, "english_name": "The Rocky Tract", "description": "A Meccan streamprotected_cb2 reassuring the Prophet (Peace be upon him) against mockery and detailing the story of Satan's refusal to bow to Adam (Peace be upon him). (99 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 16, "english_name": "The Bee", "description": "A Meccan streamprotectedtrack_c-ee2 calling attention to God's blessings in nature, specifically the bee, and warning against associating partners with God. (128 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 17, "english_name": "The Night Journey", "description": "Commemorates the Prophet Muhammad's (Peace be upon him) miraculous night journey from Mecca to Jerusalem and ascension to the heavens, establishing the five daily prayers. (111 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 18, "english_name": "The Cave", "description": "A Meccan streamprotected_cb2 telling the story of the Sleepers of the Cave and Moses (Peace be upon him), focusing on maintaining faith during times of trial. (110 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 19, "english_name": "Mary", "description": "A Meccan streamprotectedtrack_c-ee2 detailing the miraculous births of Jesus (Peace be upon him) and John (Peace be upon him), emphasizing God's mercy and refuting the concept of God having a son. (98 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 20, "english_name": "Ta-Ha", "description": "Revealed in Mecca, this streamprotected_cb2 details the story of Moses (Peace be upon him) confronting Pharaoh and offers comfort to the Prophet Muhammad (Peace be upon him). (135 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 21, "english_name": "The Prophets", "description": "A Meccan text referencing many prophets (Peace be upon them) to show the continuity of the divine message and the inevitability of Judgment Day. (112 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 22, "english_name": "The Pilgrimage", "description": "A Medinan streamprotected_cb2 establishing the rituals of the Hajj pilgrimage and giving permission to believers to defend themselves against oppression. (78 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 23, "english_name": "The Believers", "description": "Revealed in Mecca, outlining the moral qualities of true believers and the miraculous stages of human embryonic development. (118 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 24, "english_name": "The Light", "description": "A Medinan streamprotectedtrack_c-ee2 focusing on social ethics, laws against slander (specifically regarding Aisha, may Allah be pleased with her), and the famous 'streamprotectedcase_c-ww2 of Light'. (64 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 25, "english_name": "The Criterion", "description": "A Meccan streamprotected_cb2 distinguishing right from wrong, answering objections raised against the streambasesecured_ca6, and describing the virtues of the 'Servants of the Most Merciful'. (77 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 26, "english_name": "The Poets", "description": "A Meccan streamprotectedtrack_c-ee2 recounting the struggles of past prophets (Peace be upon them) and criticizing poets who mislead people with falsehoods. (227 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 27, "english_name": "The Ant", "description": "Revealed in Mecca, featuring the story of Solomon (Peace be upon him), the Queen of Sheba, and the ant, emphasizing knowledge and gratitude. (93 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 28, "english_name": "The Stories", "description": "A Meccan streamprotected_cb2 detailing the life of Moses (Peace be upon him) from infancy to prophethood, contrasting his strength with the arrogance of Pharaoh and Karun. (88 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 29, "english_name": "The Spider", "description": "A Meccan streamprotectedtrack_c-ee2 using the metaphor of a spider's web to describe the fragility of false beliefs and emphasizing the necessity of testing one's faith. (69 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 30, "english_name": "The Romans", "description": "A Meccan streamprotected_cb2 predicting the victory of the Romans over the Persians, serving as a sign of God's power and the eventual triumph of the believers. (60 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 31, "english_name": "Luqman", "description": "A Meccan streamprotectedtrack_c-ee2 containing the wise advice of Luqman to his son regarding monotheism, prayer, patience, and humility. (34 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 32, "english_name": "The Prostration", "description": "A Meccan streamprotected_cb2 emphasizing the truth of the Revelation, the creation of man from clay, and the rewards for those who fall in prostration to God. (30 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 33, "english_name": "The Combined Forces", "description": "A Medinan streamprotectedtrack_c-ee2 dealing with the Battle of the Trench, the status of the Prophet's wives (may Allah be pleased with them), and the finality of Muhammad's (Peace be upon him) prophethood. (73 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 34, "english_name": "Sheba", "description": "A Meccan streamprotected_cb2 contrasting the gratitude of David (Peace be upon him) and Solomon (Peace be upon him) with the ingratitude of the people of Sheba. (54 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 35, "english_name": "The Originator", "description": "A Meccan streamprotectedtrack_c-ee2 praising God as the Originator of creation and the angels, emphasizing that all power and honor belong to Him alone. (45 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 36, "english_name": "Ya-Sin", "description": "Known as the heart of the streambasesecured_ca6, this Meccan streamprotected_cb2 focuses on the message of the Prophet (Peace be upon him), the signs of God in nature, and the resurrection. (83 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 37, "english_name": "Those Who Set The Ranks", "description": "A Meccan streamprotectedtrack_c-ee2 describing the ranks of angels and recounting the stories of Abraham (Peace be upon him) and his willingness to sacrifice his son. (182 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 38, "english_name": "The Letter Saad", "description": "A Meccan streamprotected_cb2 mentioning the patience of David (Peace be upon him), Solomon (Peace be upon him), and Job (Peace be upon him), and warning against arrogance. (88 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 39, "english_name": "The Troops", "description": "A Meccan streamprotectedtrack_c-ee2 emphasizing the sincerity of religion for God alone and the distinct separation between believers and disbelievers in the Hereafter. (75 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 40, "english_name": "The Forgiver", "description": "A Meccan streamprotected_cb2, the first of the Ha-Mim series, discussing the struggle between truth and falsehood and the story of the Believer in Pharaoh's court. (85 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 41, "english_name": "Explained in Detail", "description": "A Meccan streamprotectedtrack_c-ee2 detailing the nature of the streambasesecured_ca6 as a guide and warning, and the testimony of one's own skin against them on Judgment Day. (54 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 42, "english_name": "The Consultation", "description": "A Meccan streamprotected_cb2 emphasizing the unity of the divine message and the importance of consultation (Shura) among believers. (53 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 43, "english_name": "The Ornaments of Gold", "description": "A Meccan streamprotectedtrack_c-ee2 criticizing the materialistic values of the disbelievers and asserting that true honor comes from faith, not wealth. (89 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 44, "english_name": "The Smoke", "description": "A Meccan streamprotected_cb2 warning of a coming punishment (smoke) and recounting the fate of Pharaoh and his people as a lesson. (59 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 45, "english_name": "The Crouching", "description": "A Meccan streamprotectedtrack_c-ee2 describing the humiliation of the arrogant on Judgment Day when every nation will be kneeling before God. (37 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 46, "english_name": "The Wind-Curved Sandhills", "description": "A Meccan streamprotected_cb2 mentioning the people of 'Ad and warning the Quraish of the consequences of rejecting the message. (35 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 47, "english_name": "Muhammad", "description": "A Medinan streamprotectedtrack_c-ee2 focusing on the test of faith through struggle and the clear distinction between the followers of truth and falsehood. (38 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 48, "english_name": "The Victory", "description": "Revealed after the Treaty of Hudaibiyah, declaring it a clear victory and promising forgiveness and tranquility to the believers. (29 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 49, "english_name": "The Rooms", "description": "A Medinan streamprotected_cb2 establishing the code of conduct for the Muslim community, including manners with the Prophet (Peace be upon him) and brotherhood. (18 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 50, "english_name": "The Letter Qaf", "description": "A Meccan streamprotectedtrack_c-ee2 dealing with the resurrection and the recording of deeds by the two angels sitting on the right and left. (45 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 51, "english_name": "The Winnowing Winds", "description": "A Meccan streamprotected_cb2 affirming the truth of the Day of Judgment and the purpose of creating Jinn and Mankind: to worship God. (60 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 52, "english_name": "The Mount", "description": "A Meccan streamprotectedtrack_c-ee2 swearing by Mount Sinai to confirm the punishment of the disbelievers and the bliss of the righteous. (49 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 53, "english_name": "The Star", "description": "A Meccan streamprotected_cb2 confirming the divine source of the Prophet's (Peace be upon him) revelation and describing his vision of the Angel Gabriel. (62 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 54, "english_name": "The Moon", "description": "A Meccan streamprotectedtrack_c-ee2 starting with the splitting of the moon, a miracle of the Prophet (Peace be upon him), and warning of the Hour. (55 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 55, "english_name": "The Beneficent", "description": "A Medinan streamprotected_cb2 listing the countless favors of God and repeatedly asking, 'Which of the favors of your Lord will you deny?' (78 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 56, "english_name": "The Inevitable", "description": "A Meccan streamprotectedtrack_c-ee2 categorizing people into three groups on Judgment Day: the Foremost, the Companions of the Right, and the Companions of the Left. (96 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 57, "english_name": "The Iron", "description": "A Medinan streamprotected_cb2 encouraging charity and sacrifice, and mentioning iron as a tool sent down by God for the benefit of humanity. (29 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 58, "english_name": "The Pleading Woman", "description": "A Medinan streamprotectedtrack_c-ee2 addressing the issue of Zihar (a pre-Islamic form of divorce) and emphasizing God's omniscience. (22 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 59, "english_name": "The Exile", "description": "A Medinan streamprotected_cb2 dealing with the banishment of the Banu Nadir tribe and the distribution of their property. (24 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 60, "english_name": "She That Is To Be Examined", "description": "A Medinan streamprotectedtrack_c-ee2 instructing believers on how to deal with women who migrate from Mecca and the limits of loyalty to non-believers. (13 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 61, "english_name": "The Ranks", "description": "A Medinan streamprotected_cb2 calling believers to strive in the cause of God and predicting the coming of a messenger named Ahmad (Muhammad, Peace be upon him). (14 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 62, "english_name": "The Congregation", "description": "A Medinan streamprotectedtrack_c-ee2 emphasizing the importance of the Friday prayer and abandoning trade when the call to prayer is heard. (11 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 63, "english_name": "The Hypocrites", "description": "A Medinan streamprotected_cb2 exposing the deceit of the hypocrites and warning believers not to let wealth and children distract them from God. (11 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 64, "english_name": "The Mutual Disillusion", "description": "A Medinan streamprotectedtrack_c-ee2 describing the Day of Judgment as a day of mutual loss and gain, and affirming that nothing happens without God's permission. (18 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 65, "english_name": "The Divorce", "description": "A Medinan streamprotected_cb2 detailing the laws of divorce and the waiting period (Iddah), emphasizing piety and trust in God. (12 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 66, "english_name": "The Prohibition", "description": "A Medinan streamprotectedtrack_c-ee2 addressing a domestic incident in the Prophet's (Peace be upon him) household and calling for sincere repentance. (12 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 67, "english_name": "The Sovereignty", "description": "A Meccan streamprotected_cb2 affirming God's dominion over life and death and urging reflection on the perfection of His creation. (30 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 68, "english_name": "The Pen", "description": "A Meccan streamprotectedtrack_c-ee2 defending the sanity and character of the Prophet (Peace be upon him) and telling the story of the owners of the garden. (52 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 69, "english_name": "The Reality", "description": "A Meccan streamprotected_cb2 describing the inevitable destruction of past nations who denied the truth and the events of the Last Day. (52 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 70, "english_name": "The Ascending Stairways", "description": "A Meccan streamprotectedtrack_c-ee2 describing the lengthy nature of the Day of Judgment and the psychological state of the disbelievers. (44 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 71, "english_name": "Noah", "description": "A Meccan streamprotected_cb2 devoted to the preaching of Noah (Peace be upon him) and his prayer for the destruction of the defiant disbelievers. (28 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 72, "english_name": "The Jinn", "description": "A Meccan streamprotectedtrack_c-ee2 recounting the story of a group of Jinn who listened to the streambasesecured_ca6 and embraced Islam. (28 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 73, "english_name": "The Enshrouded One", "description": "A Meccan streamprotected_cb2 commanding the Prophet (Peace be upon him) to rise for night prayer and to bear patience with the opposition. (20 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 74, "english_name": "The Cloaked One", "description": "A Meccan streamprotectedtrack_c-ee2 commanding the Prophet (Peace be upon him) to arise and warn, and describing the Hellfire. (56 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 75, "english_name": "The Resurrection", "description": "A Meccan streamprotected_cb2 emphasizing the physical resurrection and the care taken in the revelation and compilation of the streambasesecured_ca6. (40 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 76, "english_name": "The Man", "description": "A Medinan streamprotectedtrack_c-ee2 describing the creation of man and the rewards of the righteous in Paradise, specifically referencing the family of the Prophet (Peace be upon him). (31 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 77, "english_name": "The Emissaries", "description": "A Meccan streamprotected_cb2 swearing by the winds to affirm the reality of Judgment Day and the destruction of those who deny it. (50 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 78, "english_name": "The Tidings", "description": "A Meccan streamprotectedtrack_c-ee2 questioning the disbelievers about the Great News (Resurrection) and describing the Day of Decision. (40 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 79, "english_name": "Those Who Drag Forth", "description": "A Meccan streamprotected_cb2 describing the angels who extract souls and the story of Moses (Peace be upon him) and Pharaoh. (46 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 80, "english_name": "He Frowned", "description": "A Meccan streamprotectedtrack_c-ee2 correcting the Prophet (Peace be upon him) for turning away from a blind man to attend to a wealthy leader. (42 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 81, "english_name": "The Overthrowing", "description": "A Meccan streamprotected_cb2 describing the cosmic upheavals on the Day of Judgment and affirming the truthfulness of the Messenger (Peace be upon him). (29 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 82, "english_name": "The Cleaving", "description": "A Meccan streamprotectedtrack_c-ee2 describing the splitting of the sky and the recording of deeds by the guardian angels. (19 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 83, "english_name": "The Defrauding", "description": "A Meccan streamprotected_cb2 warning those who cheat in weights and measures and describing the record of the wicked and the righteous. (36 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 84, "english_name": "The Sundering", "description": "A Meccan streamprotectedtrack_c-ee2 describing the inevitable return to God and the giving of the record of deeds. (25 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 85, "english_name": "The Mansions of the Stars", "description": "A Meccan streamprotected_cb2 recounting the story of the People of the Ditch who were burned for their faith, and affirming God's power. (22 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 86, "english_name": "The Morning Star", "description": "A Meccan streamprotectedtrack_c-ee2 reminding man of his creation and affirming that every soul has a guardian. (17 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 87, "english_name": "The Most High", "description": "A Meccan streamprotected_cb2 glorifying God and promising the Prophet (Peace be upon him) that he will not forget the revelation. (19 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 88, "english_name": "The Overwhelming", "description": "A Meccan streamprotectedtrack_c-ee2 contrasting the state of the frightened disbelievers and the joyful believers on Judgment Day. (26 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 89, "english_name": "The Dawn", "description": "A Meccan streamprotected_cb2 mentioning the fate of 'Ad, Thamud, and Pharaoh, and the peaceful soul returning to its Lord. (30 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 90, "english_name": "The City", "description": "A Meccan streamprotectedtrack_c-ee2 defining the difficult path of virtue as freeing slaves, feeding the poor, and having patience. (20 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 91, "english_name": "The Sun", "description": "A Meccan streamprotected_cb2 linking the purification of the soul to success and its corruption to failure. (15 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 92, "english_name": "The Night", "description": "A Meccan streamprotectedtrack_c-ee2 contrasting those who give and fear God with those who are miserly and arrogant. (21 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 93, "english_name": "The Morning Hours", "description": "A Meccan streamprotected_cb2 reassuring the Prophet (Peace be upon him) that God has not forsaken him and reminding him of God's past favors. (11 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 94, "english_name": "The Relief", "description": "A Meccan streamprotectedtrack_c-ee2 comforting the Prophet (Peace be upon him) by promising that ease follows hardship. (8 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 95, "english_name": "The Fig", "description": "A Meccan streamprotected_cb2 stating that man was created in the best stature but can fall to the lowest of the low if he lacks faith. (8 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 96, "english_name": "The Clot", "description": "The first five streamprotectedcase_cww2s were the first revelation to the Prophet (Peace be upon him), commanding him to read in the name of his Lord. (19 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 97, "english_name": "The Power", "description": "A Meccan streamprotectedtrack_c-ee2 describing the Night of Power (Laylat al-Qadr), which is better than a thousand months. (5 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 98, "english_name": "The Clear Proof", "description": "A Medinan streamprotected_cb2 addressing the People of the Scripture and the polytheists, stating that true religion is sincere worship of God. (8 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 99, "english_name": "The Earthquake", "description": "A Medinan streamprotectedtrack_c-ee2 describing the violent shaking of the earth on Judgment Day and the exposure of all deeds. (8 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 100, "english_name": "The Courser", "description": "A Meccan streamprotected_cb2 swearing by the panting war horses to describe man's ingratitude and love for wealth. (11 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 101, "english_name": "The Calamity", "description": "A Meccan streamprotectedtrack_c-ee2 describing the shock of the Day of Judgment when people will be like scattered moths. (11 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 102, "english_name": "The Rivalry in World Increase", "description": "A Meccan streamprotected_cb2 warning against the distraction of accumulating worldly wealth until one visits the graves. (8 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 103, "english_name": "The Declining Day", "description": "A Meccan streamprotectedtrack_c-ee2 stating that all mankind is in loss except those who believe, do good, and advise each other to truth and patience. (3 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 104, "english_name": "The Traducer", "description": "A Meccan streamprotected_cb2 warning against backbiting and hoarding wealth, threatening the punishment of the 'Crusher'. (9 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 105, "english_name": "The Elephant", "description": "A Meccan streamprotectedtrack_c-ee2 recounting God's protection of the Kaaba from the army of Abraha and his elephants. (5 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 106, "english_name": "Quraish", "description": "A Meccan streamprotected_cb2 calling upon the Quraish tribe to worship the Lord of the House (Kaaba) who provided them with security and sustenance. (4 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 107, "english_name": "The Small Kindnesses", "description": "A Meccan streamprotectedtrack_c-ee2 condemning those who deny the Judgment, neglect prayer, and refuse small acts of kindness. (7 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 108, "english_name": "The Abundance", "description": "The shortest streamprotected_cb2, revealing God's promise of abundance to the Prophet (Peace be upon him) and the cutting off of his enemies. (3 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 109, "english_name": "The Disbelievers", "description": "A Meccan streamprotectedtrack_c-ee2 declaring the absolute separation of worship between Muslims and disbelievers: 'To you be your religion, and to me my religion.' (6 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 110, "english_name": "The Divine Support", "description": "A Medinan streamprotected_cb2 predicting the mass entry of people into Islam and commanding the Prophet (Peace be upon him) to glorify God. (3 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 111, "english_name": "The Palm Fiber", "description": "A Meccan streamprotectedtrack_c-ee2 condemning Abu Lahab, an uncle and enemy of the Prophet (Peace be upon him), and his wife. (5 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 112, "english_name": "The Sincerity", "description": "A Meccan streamprotected_cb2 describing the absolute Oneness and eternal nature of God, who has no parent or child. (4 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 113, "english_name": "The Daybreak", "description": "A Meccan streamprotectedtrack_c-ee2 seeking refuge in God from the evil of created things, darkness, sorcery, and envy. (5 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 114, "english_name": "The Mankind", "description": "A Meccan streamprotected_cb2 seeking refuge in the Lord of mankind from the whispers of Satan and evil people. (6 streamprotectedcase_cww2)" }
    ];

    // 2. CONFIG
    const translations = {
        'en': { name: 'English', url: '/media/data/en.sahih.xml' },
        'id': { name: 'Indonesian', url: '/media/data/id.indonesian.xml' },
        'fr': { name: 'French', url: '/media/data/fr.hamidullah.xml' },
        'es': { name: 'Spanish', url: '/media/data/es.cortes.xml' },
        'ur': { name: 'Urdu', url: '/media/data/ur.jalandhry.xml' },
        'tr': { name: 'Turkish', url: '/media/data/tr.yuksel.xml' },
        'ru': { name: 'Russian', url: '/media/data/ru.kuliev.xml' },
        'cn': { name: 'Chinese', url: '/media/data/zh.jian.xml' },
        'de': { name: 'German', url: '/media/data/de.aburida.xml' },
        'it': { name: 'Italian', url: '/media/data/it.piccardo.xml' },
        'pt': { name: 'Portuguese', url: '/media/data/pt.elhayek.xml' },
        'ml': { name: 'Malayalam', url: '/media/data/ml.abdulhameed.xml' },
        'fa': { name: 'Persian', url: '/media/data/fa.ghomshei.xml' },
        'sw': { name: 'Swahili', url: '/media/data/sw.barwani.xml' },
        'th': { name: 'Thai', url: '/media/data/th.thai.xml' },
        'nl': { name: 'Dutch', url: '/media/data/nl.keyzer.xml' },
        'ja': { name: 'Japanese', url: '/media/data/ja.japanese.xml' },
        'ko': { name: 'Korean', url: '/media/data/ko.korean.xml' },
        'sv': { name: 'Swedish', url: '/media/data/sv.bernstrom.xml' },
        'vi': { name: 'Vietnamese', url: '/media/data/vi.hassan.xml' },
        'bg': { name: 'Bulgarian', url: '/media/data/bg.theophanov.xml' },
        'bs': { name: 'Bosnian', url: '/media/data/bs.mlivo.xml' },
        'cs': { name: 'Czech', url: '/media/data/cs.hrbek.xml' },
        'ha': { name: 'Hausa', url: '/media/data/ha.gumi.xml' },
        'ms': { name: 'Malay', url: '/media/data/ms.basmeih.xml' },
        'no': { name: 'Norwegian', url: '/media/data/no.einar.xml' },
        'pl': { name: 'Polish', url: '/media/data/pl.bielawskiego.xml' },
        'ro': { name: 'Romanian', url: '/media/data/ro.grigore.xml' },
        'so': { name: 'Somali', url: '/media/data/so.abduh.xml' },
        'sq': { name: 'Albanian', url: '/media/data/sq.ahmeti.xml' },
        'ta': { name: 'Tamil', url: '/media/data/ta.tamil.xml' },
        'tt': { name: 'Tatar', url: '/media/data/tt.nugman.xml' },
        'ug': { name: 'Uyghur', url: '/media/data/ug.saleh.xml' },
        'uz': { name: 'Uzbek ', url: '/media/data/uz.sodik.xml' }
    };

    // 3. RECITERS
    const RECITERS_CONFIG = {
        'alafasy': { name: 'Mishary Alafasy', path: 'Alafasy_128kbps' },
        'juhaynee': { name: 'Al Juhany', path: 'Abdullaah_3awwaad_Al-Juhaynee_128kbps' },
        'sudais': { name: 'As Sudais', path: 'Abdurrahmaan_As-Sudais_192kbps' },
        'ghamadi': { name: 'Al Ghamdi', path: 'Ghamadi_40kbps' },
        'abbad': { name: 'Fares Abbad', path: 'Fares_Abbad_64kbps' },
        'muaiqly': { name: 'Al Muaiqly', path: 'MaherAlMuaiqly128kbps' },
        'shuraym': { name: 'Ash Shuraym', path: 'Saood_ash-Shuraym_128kbps' },
        'basit': { name: 'Abdul Basit', path: 'Abdul_Basit_Murattal_192kbps' },
        'ayyoub': { name: 'Muhammad Ayyoub', path: 'Muhammad_Ayyoub_128kbps' },
        'shatri': { name: 'Ash Shatri', path: 'Abu_Bakr_Ash-Shatri_128kbps' },
        'hudhaify': { name: 'Al Hudhaify', path: 'Ali_Jaber_64kbps' },
        'akhdar': { name: 'Ibrahim Al-Akhdar', path: 'Ibrahim_Al-Akhdar_32kbps' },
        'matrud': { name: 'Al Matrud', path: 'Abdullah_Matroud_128kbps' },
        'basit_mjwd': { name: 'Abdul Basit (Mujawwad)', path: 'Abdul_Basit_Mujawwad_128kbps' },
        'minshawi': { name: 'Al Minshawi', path: 'Minshawy_Murattal_128kbps' },
        'minshawi_mjwd': { name: 'Al Minshawi (Mujawwad)', path: 'Minshawy_Mujawwad_192kbps' },
        'tablawi': { name: 'At Tablawi', path: 'Mohammad_al_Tablaway_128kbps' },
        'hussary': { name: 'Al Hussary', path: 'Husary_128kbps' },
        'hussary_mjwd': { name: 'Al Hussary (Mujawwad)', path: 'Husary_Mujawwad_128kbps' }
    };

    return new Response(JSON.stringify({
        streamprotectedtrack_cee2: streamprotected_cb2_METADATA,
        translations: translations,
        streamprotectedlicense_artists_cr1: RECITERS_CONFIG
    }), {
        headers: { "Content-Type": "application/json" }
    });
}